spring.application.name=univCabi
spring.config.import=optional:file:.env

# Redis ??
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.database=0

# Add these properties to your application.properties or application.yml file

# Kafka connection settings
spring.kafka.bootstrap-servers=localhost:9092

# Producer settings
spring.kafka.producer.retries=5
spring.kafka.producer.acks=all
spring.kafka.producer.batch-size=16384
spring.kafka.producer.buffer-memory=33554432
spring.kafka.producer.properties.request.timeout.ms=30000
spring.kafka.producer.properties.retry.backoff.ms=500

# Consumer settings
spring.kafka.consumer.group-id=locker-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.auto-commit-interval=1000
spring.kafka.consumer.max-poll-records=500
spring.kafka.consumer.properties.request.timeout.ms=30000
spring.kafka.consumer.properties.session.timeout.ms=60000

# Listener settings
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.listener.concurrency=3
spring.kafka.listener.ack-mode=RECORD

# General retry and backoff settings
spring.kafka.properties.reconnect.backoff.ms=1000
spring.kafka.properties.reconnect.backoff.max.ms=10000
spring.kafka.properties.retry.backoff.ms=500

# Set to true for local development when Kafka might not be available
spring.kafka.bootstrap-servers-optional=true

logging.level.org.apache.kafka=WARN


# ?????? ?? ??
spring.datasource.url=jdbc:mysql://localhost:3306/mysql_univcabi?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ?? - ? ???? ??
spring.jpa.hibernate.ddl-auto=create
# MySQL8Dialect? ? ?? ????? ??? ??? ???? ?? ?? ??
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JPA ??? ? SQL ???? ??
spring.jpa.defer-datasource-initialization=true

# SQL ??? ??
spring.sql.init.mode=always
spring.sql.init.continue-on-error=false
spring.sql.init.data-locations=classpath:db/migration/V1__Flush_all_data.sql,classpath:db/migration/V2__Insert_building_data.sql,classpath:db/migration/V3__Insert_user_data.sql,classpath:db/migration/V4__Insert_authn_data.sql,classpath:db/migration/V5__Insert_cabinet_data.sql,classpath:db/migration/V6__Insert_cabinet_position_data.sql,classpath:db/migration/V7__Insert_playable_data.sql

# JWT ??
jwt.secret=${JWT_SECRET_KEY}
jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION}
jwt.refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION}

